### ISSUE TITLE
Advice

### ISSUE THREAD

**Issue by KIRANKUMAR7296** [Laxman-Parab/portfolio#1]
@Laxman-Parab  
Please remove the **tag manager** script from your head tag, 
I am able to track the movements on your portfolio, 
I have also attached screenshot of your webpage.

![Remove](https://user-images.githubusercontent.com/61859813/130557461-f1159238-75fd-44ac-b2ee-ae701026abe1.png)

**Comment by Laxman-Parab** [comment]
Oh Damn! I'm sorry for the inconveniences!
Also thanks for that inspiration. 🙏🏻

**Comment by KIRANKUMAR7296** [comment]
No problem
Learn, Implement & Share.
